skip building PRoot on ppc64le and s390x arches
Signed-off-by: Dave Dykstra <2129743+DrDaveD@users.noreply.github.com>

diff --git a/scripts/compile-dependencies b/scripts/compile-dependencies
--- a/scripts/compile-dependencies
+++ b/scripts/compile-dependencies
@@ -21,8 +21,8 @@ set -ex
 for PKG in squashfs-tools squashfuse e2fsprogs fuse-overlayfs gocryptfs PRoot; do
     TGZ="$(echo $SRC/${PKG}[_-]*.tar.gz)"
     if [ ! -f "$TGZ" ]; then
-	echo "\$PKG[_-]*.tar.gz not found in $SRC" >&2
-	exit 1
+	echo "\$PKG[_-]*.tar.gz not found in $SRC, skipping" >&2
+	continue
     fi
     DIR=${TGZ%.tar.gz}
     DIR=${DIR/*\//}
diff --git a/scripts/install-dependencies b/scripts/install-dependencies
--- a/scripts/install-dependencies
+++ b/scripts/install-dependencies
@@ -35,8 +35,8 @@ fi
 set -ex
 for CMD in squashfs-tools-*/squashfs-tools/{mksquashfs,unsquashfs} squashfuse-*/squashfuse_ll e2fsprogs-*/fuse2fs fuse-overlayfs-*/fuse-overlayfs gocryptfs[_-]*/gocryptfs PRoot-*/src/proot; do
     if [ ! -f "$CMD" ]; then
-	echo "$CMD not found" >&2
-	exit 1
+	echo "$CMD not found, skipping" >&2
+	continue
     fi
     cp -f $CMD $DIR
 done
